Beautify #12
marinasessim/Maglite pull request #13
Opened 2017-07-12 17:17 UTC by marinasessim

2017-07-12 19:49 UTC, snschune requested changes
See if you can work in these suggestions. Then we'll need to squash these commits. After that I'll look at it again. I got confused by files being modified multiple times.

2017-07-12 19:49 UTC, snschune commented on include/userobject/ElasticRecoilCrossSectionUserObject.h
> +  std::string _file_name;
you're already verbose here, why not call it `_output_file_name`?

2017-07-12 19:49 UTC, snschune commented on src/userobject/ElasticRecoilCrossSectionUserObject.C
>    return params;
I'd like you to add 
`params.addClassDescription("")` where the purpose and output format of the class is explained.

2017-07-12 19:49 UTC, snschune commented on examples/H_example.i
> -[Mesh]
I am not sure why this is here? Can it be squashed away somehow?

2017-07-12 19:49 UTC, snschune commented on examples/matplotlib/anlt_check_mu_o.py
> +import numpy as np
I won't review this file, since it won't be in the Magpie commit anyway.

2017-07-12 19:49 UTC, snschune commented on include/userobject/ElasticRecoilCrossSectionUserObject.h
> +  Real shiftedLP(unsigned int n, Real x);
does the latest implementation use the `shiftedLP`? If not we should remove it.

2017-07-12 19:49 UTC, snschune commented on src/userobject/ElasticRecoilCrossSectionUserObject.C
> +  _quad_points =   {-0.999714, -0.998492, -0.996295, -0.993125, -0.988984, -0.983878,
We should find a nicer place for this than here....not sure where yet, but we can discuss it.

2017-07-12 19:49 UTC, snschune commented on src/userobject/ElasticRecoilCrossSectionUserObject.C
> +        output_file2 << _save_mu_L[t][g] << ',';
indentation

2017-07-12 19:49 UTC, snschune commented on src/userobject/ElasticRecoilCrossSectionUserObject.C
> +        output_file2 << _save_mu_L[t][g];
indentation

2017-07-12 19:49 UTC, snschune commented on src/userobject/ElasticRecoilCrossSectionUserObject.C
> +/*
remove these commented lines? Or are they removed in final commit?

2017-07-12 19:49 UTC, snschune commented on src/userobject/ElasticRecoilCrossSectionUserObject.C
> +        output_file2 << _save_mu_L[t][g][0] << ',' << _save_mu_L[t][g][1] << ',';
is this ordered `min, max` or `max, min`? The former is more logical.

2017-07-12 21:06 UTC, marinasessim commented
Ok, I thought the new branch would stash all commits automatically. I'll look into all the changes.

2017-07-13 16:35 UTC, snschune approved these changes

2017-07-13 16:37 UTC, merged